CREATE TABLE STUDENT
(
	ROLL INT PRIMARY KEY,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30),
    AGE INT CHECK(AGE>5),
    CLASS INT NOT NULL
);
CREATE TABLE COURSE
(
	ID CHAR(4) PRIMARY KEY,
    CODE CHAR(10) NOT NULL,
    CREDIT INT NOT NULL,
    UNIVERSITY VARCHAR(50) NOT NULL
);
CREATE TABLE ENROLL
(
	ID CHAR(4) PRIMARY KEY,
    ROLL INT,
    COURSE_ID CHAR(4),
    FOREIGN KEY(ROLL)
		REFERENCES STUDENT(ROLL)
		ON DELETE CASCADE,
    FOREIGN KEY(COURSE_ID)
		REFERENCES COURSE(ID)
        ON DELETE SET NULL
);