CREATE DATABASE ASSIGNMENT2;

USE ASSIGNMENT2;

CREATE TABLE DEPARTMENTS
(
	DEPARTMENT_ID CHAR(4) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(40) NOT NULL    
);

CREATE TABLE EMPLOYEES
(
	EMPLOYEE_ID CHAR(4) PRIMARY KEY,
	FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30),
    DATE_OF_BIRTH DATE NOT NULL,
    DEPARTMENT_ID CHAR(4),
    SALARY INT NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

USE DUMMYDB;

-- Write SQL Query to get the second max salary 
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < (SELECT MAX(SALARY)
				FROM EMPLOYEES);
                
-- Write SQL Query to show  the department names and the average salary of the departments

SELECT DEP.DEPARTMENT_NAME,
	(SELECT AVG(SALARY) 
    FROM EMPLOYEES WHERE 
    DEPARTMENT_ID = DEP.DEPARTMENT_ID)
    AS AVEREGE_SALARY
FROM DEPARTMENTS AS DEP;

-- What is a subquery? Write with an example

-- we can get 2nd minium salary with the below subquery
SELECT MIN(SALARY)
FROM EMPLOYEES
WHERE SALARY > (SELECT MIN(SALARY) FROM EMPLOYEES);

-- Show the names of the employees who get less salary than Steven
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE SALARY < (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME = 'STEVEN' LIMIT 1);

-- Count the number of employees of each job type

SELECT JOB_TITLE, (SELECT COUNT(*) FROM EMPLOYEES WHERE JOB_ID = JOBS.JOB_ID) AS EMPLOYEE_COUNT
FROM JOBS;

-- Show the names of Departments which doesn’t have any employees

SELECT DEP.DEPARTMENT_NAME
FROM DEPARTMENTS AS DEP LEFT JOIN EMPLOYEES AS EMP USING(DEPARTMENT_ID)
WHERE EMP.EMPLOYEE_ID IS NULL