-- FIND THOSE DEPARTMENTS WHICH HAS NO EMPLOYEES
SELECT DEP.DEPARTMENT_NAME
FROM DEPARTMENTS AS DEP LEFT JOIN EMPLOYEES AS EMP USING(DEPARTMENT_ID)
WHERE EMP.EMPLOYEE_ID IS NULL;


SELECT 
	EMP.FIRST_NAME, EMP.SALARY, EMP.DEPARTMENT_ID,
    ( SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = EMP.DEPARTMENT_ID)
    - EMP.SALARY AS SALARY_KOM_PAI
FROM EMPLOYEES AS EMP JOIN DEPARTMENTS AS DEP USING(DEPARTMENT_ID);

SELECT AVG(SALARY)
FROM EMPLOYEES WHERE DEPARTMENT_ID = 60;

SELECT DEPARTMENT_NAME
FROM EMPLOYEES JOIN DEPARTMENTS USING(DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME
HAVING MIN(SALARY) > 5000



